import { StyleSheet } from 'react-native';

export const TYPE_COLORS: Record<string, string> = {
    fire: '#F08030',
    water: '#6890F0',
    grass: '#78C850',
    electric: '#F8D030',
    psychic: '#F85888',
    ice: '#98D8D8',
    dragon: '#7038F8',
    dark: '#705848',
    normal: '#A8A878',
    fighting: '#C03028',
    flying: '#A890F0',
    poison: '#A040A0',
    ground: '#E0C068',
    rock: '#B8A038',
    bug: '#A8B820',
    ghost: '#705898',
    steel: '#B8B8D0',
    fairy: '#EE99AC',
};

export const TYPE_TEXT_COLORS: Record<string, string> = {
    electric: '#5a4a00',
    normal: '#3a3a2a',
    ground: '#5a4a00',
    rock: '#3a3200',
    bug: '#3a4000',
    ice: '#1a4a4a',
    steel: '#2a2a40',
};

export const Styles = StyleSheet.create({
    card: {
        flex: 1,
        margin: 8,
        borderRadius: 16,
        padding: 12,
        alignItems: 'center',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
    },
    index: {
        alignSelf: 'flex-start',
        fontSize: 11,
        fontWeight: '700',
        opacity: 0.6,
        color: '#fff',
        letterSpacing: 0.5,
    },
    image: {
        width: 90,
        height: 90,
    },
    name: {
        fontSize: 14,
        fontWeight: '800',
        color: '#fff',
        textTransform: 'capitalize',
        marginTop: 4,
        textAlign: 'center',
        letterSpacing: 0.3,
    },
    typesRow: {
        flexDirection: 'row',
        gap: 4,
        marginTop: 6,
        flexWrap: 'wrap',
        justifyContent: 'center',
    },
    typeBadge: {
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 20,
        backgroundColor: 'rgba(255,255,255,0.25)',
    },
    typeText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#fff',
        textTransform: 'capitalize',
        letterSpacing: 0.4,
    },
    divider: {
        height: 1,
        backgroundColor: 'rgba(255,255,255,0.2)',
        width: '100%',
        marginVertical: 8,
    },
    powersContainer: {
        width: '100%',
        gap: 4,
    },
    powerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    powerName: {
        fontSize: 10,
        color: 'rgba(255,255,255,0.85)',
        textTransform: 'capitalize',
        flex: 1,
        letterSpacing: 0.2,
    },
    powerBarBackground: {
        flex: 2,
        height: 5,
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 10,
        marginHorizontal: 6,
        overflow: 'hidden',
    },
    powerBarFill: {
        height: '100%',
        backgroundColor: 'rgba(255,255,255,0.75)',
        borderRadius: 10,
    },
    powerValue: {
        fontSize: 10,
        color: '#fff',
        fontWeight: '700',
        width: 24,
        textAlign: 'right',
    },
});
